### PR TITLE
💄 add splash screen component

### LINKED ISSUE #7: add splash screen component
create splash screen for the user to feel welcomed and get familiar with the corporate identity by showing fonts and the logo.
the logo is part of #6 

image

### PR DESCRIPTION
**Pull request by RonjaMeinecke**
close #7 
• create splash screen component
• implement logo component
• update fonts

https://good-thanks-splash-scre-lcyxzk.herokuapp.com/storybook/index.html?path=/story/splashscreen--splash-screen-component

### CODE REVIEW

**Review by mhstrkmp — COMMENTED** [review]
lgtm 🚀

**Review by sweisz — APPROVED** [review]
GJ 🥇

**Review by JuKahl — APPROVED** [review]
lgtm 🥸

**Review by DNaunin — APPROVED** [review]
Great Job! 🦖

**Review by cboenke — APPROVED** [review]
GJ 🦾

**Comment by mewiemers** [comment]
LGTM🦕

**Pull request merged**
